export * from "./Login";
export * from "./SignUp";
export * from "./Dashboards";
export * from "./Cases";
export * from "./Investigators";
export * from "./Operators";
export * from "./NotFound";
export * from "./ManageOperators";
export * from "./ManageInvestigators";
export * from "./Inbox";
export * from "./ManageCriminals"
export * from "./CreateFIR";
export * from "./AllFIRs";
export * from "./FirDetail";